---
# Codepage 0 corresponds to the codepage 0 of Metapace T family of thermal printers
0:
  ä: 0x84
  ü: 0x81
  ö: 0x94
  Ä: 0x8E
  Ü: 0x9A
  Ö: 0x99
  é: 0x82
  è: 0x8A
  ú: 0xA3
  ù: 0x97
  á: 0xA0
  à: 0x85
  í: 0xA1
  ì: 0x8D
  ó: 0xA2
  ò: 0x95
  â: 0x83
  ê: 0x88
  î: 0x8C
  ô: 0x93
  û: 0x96
  ñ: 0xA4
  ß: 0xE1